name: ska-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - pip=23.3.1
  - pip:
      - matplotlib==3.7.5
      - numpy==1.24.4
      - scipy==1.10.1
      - pytest==6.2.5
      